---

- name: BUILDAH CONFIG | Registries
  template:
    src: etc/containers/registries.conf.j2
    dest: /etc/containers/registries.conf
    owner: root
    group: root
    mode: 0644

- name: BUILDAH CONFIG | Mounts
  template:
    src: usr/share/containers/mounts.conf.j2
    dest: /usr/share/containers/mounts.conf
    owner: root
    group: root
    mode: 0644

- name: BUILDAH CONFIG | Seccomp
  copy:
    src: usr/share/containers/seccomp.json
    dest: /usr/share/containers/seccomp.json
    owner: root
    group: root
    mode: 0644

- name: BUILDAH CONFIG | Policies
  copy:
    src: etc/containers/policy.json
    dest: /etc/containers/policy.json
    owner: root
    group: root
    mode: 0644
